### PR TITLE
Staging for version increment automation 

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/ml-commons/pull/1
 
### Issues Resolved
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/geospatial/issues/86
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by VijayanB — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Renaming to task updateVersion following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

**Comment by prudhvigodithi** [comment]
Hey @VijayanB  just checking back, if we are ok with PR, can we merge this?
Thank you

**Comment by VijayanB** [comment]
@martin-gaievski Can you take a look at this PR? Thanks.

**Comment by martin-gaievski** [comment]
[prudhvigodithi](https://github.com/prudhvigodithi) did you test it when build.qualifier is set? At first glance it should work but it would be nice to have a confirmation.

**Comment by prudhvigodithi** [comment]
Hey @martin-gaievski can you please elaborate, this task `updateVersion` will be called from the external [workflow](https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/increment-plugin-versions.yml) from the opensearch-build repo, all it will do is raise a version increment PR and update the required files.
@bbarani

**Comment by bbarani** [comment]
@martin-gaievski Can you please provide your inputs?

**Comment by martin-gaievski** [comment]
I think it should work, let me approve

**Review by martin-gaievski — APPROVED** [review]

**Comment by VijayanB** [comment]
@prudhvigodithi Shall i merge this PR?

**Comment by prudhvigodithi** [comment]
Hey @VijayanB yes please proceed to merge. :)

**Pull request merged**
