### PR TITLE
Add XYPoint Field Type to index and query documents that contains cartesian points

### PR DESCRIPTION
**Pull request by naveentatikonda**
### Description
Add XYPoint Field Type to index and query documents that contains cartesian points
 
### Issues Resolved
https://github.com/opensearch-project/geospatial/issues/95
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by navneet1v — COMMENTED** [review]
is this a merge commit or you have added more things on top of old PR?

**Comment by naveentatikonda** [comment]
> is this a merge commit or you have added more things on top of old PR?

No, just the merge commit

**Review by navneet1v — COMMENTED** [review]
We will be putting this as 1 single commit in main right?

**Comment by naveentatikonda** [comment]
> We will be putting this as 1 single commit in main right?

yes, we will squash all these commits and merge them into a single commit

**Review by navneet1v — APPROVED** [review]
Approving the code as all the commits in this PR is reviewed in separate PRs.

**Review by VijayanB — APPROVED** [review]

**Pull request merged**
